version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true

      - run:
          name: Make image
          command: TAG="1.0.0" make build

      - run:
          name: Print the Current Time
          command: date