version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
          
      - run:
          name: Make image
          command: docker build --pull --build-arg CACHEBUST=${CIRCLE_SHA1} -t ${IMAGE_NAME}:build .

      - run:
          name: Print the Current Time
          command: echo ${CIRCLE_TAG} ${CIRCLE_SHA1}