only-deploy-tags: &only-deploy-tags
  context: DOCKER_HUB
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/


version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          
      - run:
          name: Make image
          command: docker build --pull --build-arg CACHEBUST=${CIRCLE_SHA1} -t ${IMAGE_NAME}:build .
      
      - run:
          name: Archive Docker image
          command: docker save -o image.tar ${IMAGE_NAME}:build
      
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  tag-and-publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace 
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      # - run:
      #     name: Get versions
      #     command: |
      #       echo 'export IMAGE_TAG_PATCH="'$(docker run --rm alpine/semver semver -c patch ${CIRCLE_TAG})'"' >> $BASH_ENV
      #       echo 'export IMAGE_TAG_MINOR="'$(docker run --rm alpine/semver minor -c patch ${CIRCLE_TAG})'"' >> $BASH_ENV
      #       echo 'export IMAGE_TAG_MAJOR="'$(docker run --rm alpine/semver major -c patch ${CIRCLE_TAG})'"' >> $BASH_ENV
      - run:
          name: docker login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Pushing patch
          command: |
            IMAGE_TAG=$(docker run --rm alpine/semver semver -c patch ${CIRCLE_TAG})
            echo ${IMAGE_TAG}
            docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:${IMAGE_TAG} 
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
      - run:
          name: Pushing minor
          command: |
            IMAGE_TAG=$(docker run --rm alpine/semver semver -c minor ${CIRCLE_TAG})
            echo ${IMAGE_TAG}
            docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:${IMAGE_TAG} 
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
      - run:
          name: Pushing major
          command: |
            IMAGE_TAG=$(docker run --rm alpine/semver semver -c major ${CIRCLE_TAG})
            echo ${IMAGE_TAG}
            docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:${IMAGE_TAG} 
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
      - run:
          name: Pushing latest
          command: |
           docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:latest 
           docker push ${IMAGE_NAME}:latest

workflows:
      version: 2
      build-tag:
        jobs:
          - build: *only-deploy-tags
          - tag-and-publish:
              <<: *only-deploy-tags
              requires:
                - build