only-deploy-tags: &only-deploy-tags
  context: DOCKER_HUB
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/


version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          
      - run:
          name: Make image
          command: docker build --pull --build-arg CACHEBUST=${CIRCLE_SHA1} -t ${IMAGE_NAME}:build .
      
      - run:
          name: Archive Docker image
          command: docker save -o image.tar ${IMAGE_NAME}:build
      
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  tag-and-publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace 
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      
      - run:
          name: docker login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Get versions
          command: |
            echo 'export IMAGE_TAG_PATCH="'$(docker run --rm alpine/semver semver -c patch ${CIRCLE_TAG})'"' >> $BASH_ENV
            echo 'export IMAGE_TAG_MINOR="'$(docker run --rm alpine/semver minor -c patch ${CIRCLE_TAG})'"' >> $BASH_ENV
            echo 'export IMAGE_TAG_MAJOR="'$(docker run --rm alpine/semver major -c patch ${CIRCLE_TAG})'"' >> $BASH_ENV
            source $BASH_ENV
            echo "Patch: ${IMAGE_TAG_PATCH}"
            echo "Minor: ${IMAGE_TAG_MINOR}"
            echo "Major: ${IMAGE_TAG_MAJOR}"
      - run:
          name: Pushing patch
          command: |
            docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:${IMAGE_TAG_PATCH} 
            docker push ${IMAGE_NAME}:${IMAGE_TAG_PATCH}
      - run:
          name: Pushing minor
          command: |
            docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:${IMAGE_TAG_MINOR} 
            docker push ${IMAGE_NAME}:${IMAGE_TAG_MINOR}
      - run:
          name: Pushing major
          command: |
            docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:${IMAGE_TAG_MAJOR} 
            docker push ${IMAGE_NAME}:${IMAGE_TAG_MAJOR}
      - run:
          name: Pushing latest
          command: |
           docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:latest 
           docker push ${IMAGE_NAME}:latest

workflows:
  version: 2
  build-tag:
    jobs:
      - build: 
          context: DOCKER_HUB
          <<: *only-deploy-tags
      - tag-and-publish:
          <<: *only-deploy-tags
          requires:
            - build